In [1]:
import numpy as np

In [2]:
a1 = np.arange(15).reshape(3, 5)
print(a1,'\n',a1.shape,'\n',a1.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
 (3, 5) 
 2


In [3]:
a2 = np.arange(15)
print(a2,'\n',a2.shape,'\n',a2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
 (15,) 
 1


In [4]:
a3 = np.arange(24).reshape(3,2,4)
print(a3,'\n',a3.shape,'\n',a3.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]] 
 (3, 2, 4) 
 3


In [5]:
a4 = np.arange(24).reshape(3,2,1,4)
print(a4,'\n',a4.shape,'\n',a4.ndim)

[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]]


 [[[ 8  9 10 11]]

  [[12 13 14 15]]]


 [[[16 17 18 19]]

  [[20 21 22 23]]]] 
 (3, 2, 1, 4) 
 4


In [6]:
print('origin')
print(a3,a3.shape)
print('axis=0')
print(a3.sum(axis=0),a3.sum(axis=0).shape)
print('axis=1')
print(a3.sum(axis=1),a3.sum(axis=1).shape)
print('axis=2')
print(a3.sum(axis=2),a3.sum(axis=2).shape)
print('axis=(0,1)')
print(a3.sum(axis=(0,1)),a3.sum(axis=(0,1)).shape)
print('axis=(1,2)')
print(a3.sum(axis=(1,2)),a3.sum(axis=(1,2)).shape)
print('axis=(0,2)')
print(a3.sum(axis=(0,2)),a3.sum(axis=(0,2)).shape)
print('axis=(0,1,2)')
print(a3.sum(axis=(0,1,2)),a3.sum(axis=(0,1,2)).shape)

origin
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]] (3, 2, 4)
axis=0
[[24 27 30 33]
 [36 39 42 45]] (2, 4)
axis=1
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]] (3, 4)
axis=2
[[ 6 22]
 [38 54]
 [70 86]] (3, 2)
axis=(0,1)
[60 66 72 78] (4,)
axis=(1,2)
[ 28  92 156] (3,)
axis=(0,2)
[114 162] (2,)
axis=(0,1,2)
276 ()


In [7]:
print('axis=(0,1)')
print(a3.sum(axis=(0,1),keepdims=True),a3.sum(axis=(0,1),keepdims=True).shape)

axis=(0,1)
[[[60 66 72 78]]] (1, 1, 4)


In [11]:
ta = np.arange(24).reshape(3,2,4)
tb = np.arange(24,36).reshape(3,1,4)
print(ta,ta.shape)
print(tb,tb.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]] (3, 2, 4)
[[[24 25 26 27]]

 [[28 29 30 31]]

 [[32 33 34 35]]] (3, 1, 4)


In [16]:
print(np.concatenate((ta,tb),axis=1),np.concatenate((ta,tb),axis=1).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [24 25 26 27]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [28 29 30 31]]

 [[16 17 18 19]
  [20 21 22 23]
  [32 33 34 35]]] (3, 3, 4)
